main: com.settlercraft.claims.Claims
version: 1.0
name: Claims
api-version: 1.19
depend:
  - Settlercore
commands:
  claim:
    description: Claim a chunk
  delallcontainers:
    description: DANGER! Deletes ALL containers in a the world!
  togglelock:
    description: Toggle the lock on a container
    usage: /togglelock <lock_type>
  delclaim:
    description: Deletes the claim you're standing in
    usage: /delclaim
  convertlegacyclaims:
    description: pls work!
    usage: /convertlegacyclaims and hope for hte best!